export const textContent = {
    welcome: "Welcome",
    search: "Search",
    done: "Done",
    departure: "Departure",
    destination: "Destination",
    depDate: "Departure date",
    returnDate: "Return date",
    departureWithDots: "Departure: ",
    return: "Return: ",
    selectDeparture: "Select your departure",
    selectDestination: "Select your destination",
    selectDest: "Select destination",
    selectReturn: "Select your return date",
    selectDate: "Select date",
    dateHolder: "dd/mm/yyyy",
    roundTrip: "Round-trip",
    addPassenger: "Add passenger",
    passanger: "Passenger",
    passangers: "Passengers",
    adult: "Adult",
    adultDesc: "Above 12 years old",
    child: "Child",
    childDesc: "From 2 to 12 years old",
    baby: "Baby",
    babyDesc: "Below 2 years old",
    class: "Class",
    economy: "Economy",
    prevSearch: "Recent searches",
    popPlaces: "Popular places",
    delete: "Delete",
    emptyInfos: "Please fill in all required fields",
    noResult: "We couldn't find any result!",
    noResultDesc: "Please check your search for any typos or spelling errors, or try a different search term.",
    dummySGN: "SGN - Ho Chi Minh",
    dummyHAN: "HAN - Ha Noi, Vietnam",
    dummyDAD: "DAD - Da Nang, Vietnam",
    dummyCXR: "CXR - Nha Trang",
    dummyBMV: "BMV - Buon Me Thuot, Vietnam",
    dummyCAH: "CAH - Ca Mau, Vietnam",
    dummyDIN: "DIN - Dien Bien, Vietnam",
    dummyDLI: "DLI - Da Lat, Vietnam",
    dummyHPH: "HPH - Hai Phong, Vietnam",
    dummyHUI: "HUI - Hue, Vietnam",
    dummyPOC: "PQC - Phu Quoc, Vietnam",
    inputPlaceHolder: "City, Country..."

}
