export const textContent = {
    welcome: "Welcome",
    search: "Search",
    done: "Done",
    departure: "Departure",
    destination: "Destination",
    depDate: "Departure date",
    returnDate: "Return date",
    selectDestination: "Select your destination",
    selectDest: "Select destination",
    selectReturn: "Select your return date",
    selectDate: "Select date",
    dateHolder: "dd/mm/yyyy",
    roundTrip: "Round-trip",
    passanger: "Passenger",
    class: "Class",
    economy: "Economy",
    prevSearch: "Recent searches",
    popPlaces: "Popular places",
    delete: "Delete",
    noResult: "We couldn't find any result!",
    noResultDesc: "Please check your search for any typos or spelling errors, or try a different search term.",
    sgn: "SGN - Ho Chi Minh"

}
